### ISSUE TITLE
Failing data test

### ISSUE THREAD

**Issue by aoles** [simonpoole/OpeningHoursParser#17]
Hi,
when trying to run the tests in `DataTest` I twice get the same error in both `regressionTest()` and `regressionTestStrict()` at

```
Parser exception for 00.00-24.00 ch.poole.openinghoursparser.ParseException: Invalid minutes at 1, column 6
Parser err for 00:00-24:00; 02:00-06:00 off "Технический перерыв" org.junit.ComparisonFailure: expected:<...0; 02:00-06:00 off "[??????????? ???????]"> but was:<...0; 02:00-06:00 off "[Технический перерыв]">
Assertion failed for 00:00-24:00; 02:00-06:00 off "Технический перерыв"

expected:<[3]> but was:<[0]>
```
I was wondering whether this is an issue specific to my config, or rather a general problem? 

Cheers,
Andrzej

**Comment by simonpoole** [comment]
Hi Andrzej

IMHO all the tests should past, but at least the 2nd one could be a locale issue. I'll have a look later today (and I'll setup CI which I thought I had done, but obviously not).

**Comment by simonpoole** [comment]
Seems as if the something in the tests is not using UTF-8 .... "it used to work"

**Comment by simonpoole** [comment]
Fixed in https://github.com/simonpoole/OpeningHoursParser/commit/22c11eef69e51defc6e6c90312a52561820edb19 (background I generated the comparison files on a windows box, serves me right). 

If you look at the diff you will note that a couple of input strings succeed now that previously failed, these are ones that use non-ASCII hyphens and similar.

**Comment by aoles** [comment]
Hi Simon,

awesome - thanks a lot for getting back to me and for the prompt fix! I confirm that now all the data tests pass.

Cheers,
Andrzej
