### ISSUE TITLE
Spec allows holidays after weekdays

### ISSUE THREAD

**Issue by jb-wisemo** [simonpoole/OpeningHoursParser#48]
The syntax in the spec allows "weekday_sequence,holiday_sequence" or "holiday_sequence,weekday_sequence" (See https://wiki.openstreetmap.org/wiki/Key:opening_hours/specification )
Thus "PH,Sa-Su" and "Sa-Su,PH" are both acceptable.  But "Sa,PH,Su" is against a strict interpretation.
But the parser apparently allows "Sa-Su,PH" only in "relaxed" mode, which has already resulted in a bugreport against JOSM, which someone rejected claiming the spec didn't allow it (https://josm.openstreetmap.de/ticket/19339 )

**Comment by simonpoole** [comment]
Besides that fact that you are mistaken, because the spec didn't actually allow PH after a weekday sequence, till it was ad hoc "adjusted" (mainly because the implementation of the adjuster wasn't actually specification conformant). I've given in and the current version allows the PH after weekdays, this is also the version that JOSM currently has as a dependency. 

In summary you are barking up a non-existent tree.

**Comment by jb-wisemo** [comment]
I was not aware of the spec edit, assuming such pages were "protected".  JOSM provides an empty changelog for their latest build and none of the existing bugs mentioned the parser update, so I had to assume nothing changed at their end either.  Leaving this closed as probably fixed in latest builds.
